keys:
  # User keys
  - &user_xiphias age1sz9xddpnn9lg975lmsvt95dqfxd26qm6ymrsj0zhym23x04vmv0qmkyqmu

  # Host keys (derived from ssh-ed25519 host keys in secrets/secrets.nix)
  - &host_router 

creation_rules:
  # Secrets for all hosts
  - path_regex: secrets/sops/common\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_router
